name: 'CI Failure Summarizer'
description: 'Analyzes CI/CD failures using AI and sends human-readable summaries to Slack'
author: ''

branding:
  icon: 'alert-circle'
  color: 'red'

inputs:
  github_token:
    description: 'GitHub token to fetch workflow logs'
    required: true
    default: ${{ github.token }}
  provider:
    description: 'AI provider to use: anthropic, groq, or gemini'
    required: false
    default: 'anthropic'
  anthropic_api_key:
    description: 'Anthropic API key for Claude (required if provider is anthropic)'
    required: false
  groq_api_key:
    description: 'Groq API key (required if provider is groq) - FREE tier available'
    required: false
  gemini_api_key:
    description: 'Google Gemini API key (required if provider is gemini) - FREE tier available'
    required: false
  slack_bot_token:
    description: 'Slack Bot Token (required for DM mode, starts with xoxb-)'
    required: false
  slack_webhook_url:
    description: 'Slack incoming webhook URL (for channel mode)'
    required: false
  notification_mode:
    description: 'How to notify: "channel" (webhook) or "dm" (DM the committer)'
    required: false
    default: 'channel'
  fallback_channel:
    description: 'Channel ID to post to if DM lookup fails (e.g., C1234567890)'
    required: false
  run_id:
    description: 'Workflow run ID to analyze (defaults to current run)'
    required: false
    default: ${{ github.run_id }}
  max_log_lines:
    description: 'Maximum number of log lines to analyze (to control costs)'
    required: false
    default: '500'
  model:
    description: 'Model to use. Defaults: anthropic=claude-sonnet-4-20250514, groq=llama-3.3-70b-versatile, gemini=gemini-2.0-flash'
    required: false
  include_log_snippet:
    description: 'Include relevant log snippet in Slack message'
    required: false
    default: 'true'

outputs:
  summary:
    description: 'The AI-generated failure summary'
  slack_message_ts:
    description: 'Timestamp of the Slack message sent'
  notified_user:
    description: 'Slack user ID that was notified (in DM mode)'

runs:
  using: 'node20'
  main: 'dist/index.js'
